name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_UNSTABLE_EDITION2024: true
  RUSTUP_TOOLCHAIN: nightly

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    
    - name: Install latest Cargo
      if: matrix.os == 'ubuntu-latest'
      run: |
        rustup update
        rustup default nightly
        cargo --version
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    
    - name: Check MacOS architecture
      if: matrix.os == 'macos-latest'
      run: |
        echo "MacOS architecture: $(uname -m)"
        echo "Rust target: $(rustc -vV | grep host)"
    
    - name: Install OpenSSL (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev pkg-config
    
    - name: Install OpenSSL (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install openssl@3
        echo "OPENSSL_ROOT_DIR=$(brew --prefix openssl@3)" >> $GITHUB_ENV
        echo "OPENSSL_LIB_DIR=$(brew --prefix openssl@3)/lib" >> $GITHUB_ENV
        echo "OPENSSL_INCLUDE_DIR=$(brew --prefix openssl@3)/include" >> $GITHUB_ENV
    
    - name: Clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --all-targets --all-features -- -D warnings
    
    - name: Build (Unix)
      if: matrix.os != 'windows-latest'
      uses: actions-rs/cargo@v1
      env:
        CARGO_TERM_COLOR: always
      with:
        command: build
        args: --all-features
    
    - name: Build (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --no-default-features --features compression
    
    - name: Run tests (Unix)
      if: matrix.os != 'windows-latest'
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-features
    
    - name: Run tests (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --no-default-features --features compression
    
    - name: Security audit
      uses: actions-rs/audit-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

  compatibility:
    name: Compatibility check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Rust MSRV
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
        components: clippy
    
    - name: Build with MSRV
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --all-features

  docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
    
    - name: Build documentation
      uses: actions-rs/cargo@v1
      with:
        command: doc
        args: --no-deps --all-features

  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: llvm-tools-preview
    
    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov
    
    - name: Generate code coverage
      run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: lcov.info
        fail_ci_if_error: false 